baseURL = "https://druskus20.github.io"
languageCode = "en-us"
title = "Druskus' Website"
# publishDir = "druskus20.github.io"
summarylength = 20

# Code colors
pygmentsUseClasses = true
pygmentsCodefences = true

[permalinks]
  posts      = "posts/:year/:month/:title/"
  projects   = "projects/:title/"
#  contact-me = ":filename/"
  dump = ":filename/"

[params]
  author = "Pedro Burgos"
  description = "My personal website"
  cssFolder = "css"
  jsFolder  = "js"
